services:
  app:
    build: .
    restart: always
    env_file: .env
    expose:
      - "3000"
    volumes:
      - ./data:/app/data
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=xivbuddy
      - MYSQL_USER=xivbuddy
      - MYSQL_PASSWORD=ne8kvmewu!rGa9JzTs%e

  bot:
    build: .
    restart: always
    env_file: .env
    command: node bot.js
    volumes:
      - ./data:/app/data
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=xivbuddy
      - MYSQL_USER=xivbuddy
      - MYSQL_PASSWORD=ne8kvmewu!rGa9JzTs%e

  alert_watcher:
    build: .
    restart: always
    env_file: .env
    command: node alert_watcher.js
    volumes:
      - ./data:/app/data
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=xivbuddy
      - MYSQL_USER=xivbuddy
      - MYSQL_PASSWORD=ne8kvmewu!rGa9JzTs%e

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ne8kvmewu!rGa9JzTs%e
      MYSQL_DATABASE: xivbuddy
      MYSQL_USER: xivbuddy
      MYSQL_PASSWORD: ne8kvmewu!rGa9JzTs%e
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

volumes:
  mysql_data:
