services:
  app:
    build: .
    restart: always
    env_file: .env
    expose:
      - "3000"
    volumes:
      - ./data:/app/data
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=xivbuddy
      - MYSQL_USER=xivbuddy
      - MYSQL_PASSWORD=ne8kvmewu!rGa9JzTs%e
    networks:
      - nginx_net

  bot:
    build: .
    restart: always
    env_file: .env
    command: node bot.js
    volumes:
      - ./data:/app/data
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=xivbuddy
      - MYSQL_USER=xivbuddy
      - MYSQL_PASSWORD=ne8kvmewu!rGa9JzTs%e
    networks:
      - nginx_net

  alert_watcher:
    build: .
    restart: always
    env_file: .env
    command: node alert_watcher.js
    volumes:
      - ./data:/app/data
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=xivbuddy
      - MYSQL_USER=xivbuddy
      - MYSQL_PASSWORD=ne8kvmewu!rGa9JzTs%e
    networks:
      - nginx_net

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ne8kvmewu!rGa9JzTs%e
      MYSQL_DATABASE: xivbuddy
      MYSQL_USER: xivbuddy
      MYSQL_PASSWORD: ne8kvmewu!rGa9JzTs%e
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql



volumes:
  mysql_data:

networks:
  nginx_net:
    external: true
